name: Pipeline iOS ğŸ
on:
  push:
    tags:
      - '*'
    branches:
      - main
      - hotfix/**
      - release/**
  pull_request:
    branches:
      - feature/**
    types: [ opened, reopened, synchronize, labeled ]
  workflow_dispatch:
    inputs:
      build-ios:
        description: Build iOS app
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-ipa:
    name: ğŸš€ iOS Build
    runs-on: self-hosted
    timeout-minutes: 25
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup ruby
        run: rbenv local 3.0.0
      - name: Install Gem
        run: bundle install
      - name: Fastlane - Create keychain
        run: fastlane ios init_keychain --env alpha
      - name: Fastlane - Build
        run: fastlane ios build_ios --env alpha

